export const CACHE_KEY_CURRENT_REGION_NAME = 'QUI_REGION_NAME';
export const CACHE_KEY_AUTH_TOKEN = 'QUI_TOKEN';
export const CACHE_KEY_ORGANIZATION_ID = 'QUI_ORGANIZATION_ID';
export const CACHE_KEY_DIRECTORY_ID = 'QUI_DIRECTORY_ID';
export const CACHE_KEY_USER_SESSION = 'QUI_USER_SESSION_DATA';
export const CACHE_KEY_REDIRECT_FROM = 'QUI_REDIRECT_FROM';

